name: Tests

on:
  push:
    branches: [ main, master, e2e-relay-pinner ]
  pull_request:
    branches: [ main, master, e2e-relay-pinner ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start relay server
      run: npm run build:relay && DEBUG="le-space:*,libp2p:*" node dist/relay/index.js --test &
      env:
        NODE_ENV: test

    - name: Wait for relay server
      run: sleep 10

    - name: Run unit tests
      run: npm test

    - name: Run E2E tests
      run: npm run test:e2e
      env:
        VITE_MODE: development
        VITE_SEED_NODES_DEV: "/ip4/127.0.0.1/tcp/9092/ws/p2p/12D3KooWAJjbRkp8FPF5MKgMU53aUTxWkqvDrs4zc1VMbwRwfsbE"
        VITE_P2P_PUPSUB_DEV: "le-space._peer-discovery._p2p._pubsub"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30 