name: Tests

on:
  push:
    branches: [ main, master, e2e-relay-pinner ]
  pull_request:
    branches: [ main, master, e2e-relay-pinner ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        # cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Mocha tests
      run: npm run build:relay && npm run relay:test & npx mocha "test/**/*.test.js"

    - name: install playwright
      run: npx playwright install --with-deps

    - name: Run e2e tests
      run: npm run test:e2e
